---
- name: Install dependencies
  become: true
  hosts: localhost
  tasks:
    - name: Install basic packages
      ansible.builtin.dnf:
        name: "{{ basic_packages }}"
        state: present
        allowerasing: true
    - name: Install system tools
      ansible.builtin.dnf:
        name: "{{ sys_tools }}"
        state: present
        allowerasing: true
- import_playbook: ./playbook/neovim/playbook.yml
- import_playbook: ./playbook/wezterm/playbook.yml
- import_playbook: ./playbook/zsh/playbook.yml
- name: Install NVM
  become: false
  hosts: localhost
  tasks:
    - name: Installing
      ansible.builtin.shell:
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
- name: Install Golang 
  hosts: localhost
  become: yes
  vars:
    go_version: "1.24.3"
    go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    go_download_url: "https://go.dev/dl/{{ go_tarball }}"
    go_install_dir: "/usr/local"
  tasks:
    - name: Download Golang tarball
      get_url:
        url: "{{ go_download_url }}"
        dest: "/tmp/{{ go_tarball }}"
    - name: Extract Golang tarball
      unarchive:
        src: "/tmp/{{ go_tarball }}"
        dest: "{{ go_install_dir }}"
- name: Install Docker 
  hosts: localhost
  become: yes
  vars:
    ansible_user: saldyy
  tasks:
    - name: Add Docker CE repo
      command: >
        dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    - name: Installing
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Enable Docker
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started
- name: Install kubectl
  hosts: localhost
  become: yes
  tasks:
    - name: Download package
      shell: >
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - name: Installing
      ansible.builtin.copy:
        src: kubectl
        dest: /usr/local/bin/kubectl
        owner: root
        group: root
        mode: '0755'
    - name: Remove package
      ansible.builtin.file:
        path: ./kubectl
        state: absent
- name: Install minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Download package
      ansible.builtin.get_url:
        dest: .
        url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
    - name: Installing
      ansible.builtin.copy:
        src: minikube-linux-amd64
        dest: /usr/local/bin/minikube
        owner: root
        group: root
        mode: '0755'
    - name: Remove package
      ansible.builtin.file:
        path: ./minikube-linux-amd64
        state: absent


