---
- name: Install dependencies
  become: true
  hosts: localhost
  tasks:
    - name: Install basic packages
      ansible.builtin.dnf:
        name: "{{ basic_packages }}"
        state: present
        allowerasing: true
    - name: Install system tools
      ansible.builtin.dnf:
        name: "{{ sys_tools }}"
        state: present
        allowerasing: true
- import_playbook: ./playbook/neovim/playbook.yml
- import_playbook: ./playbook/wezterm/playbook.yml
- import_playbook: ./playbook/zsh/playbook.yml
- name: Install NVM
  become: false
  hosts: localhost
  tasks:
    - name: Installing
      ansible.builtin.shell:
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
- name: Install Golang 
  hosts: localhost
  become: yes
  vars:
    go_version: "1.24.3"
    go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    go_download_url: "https://go.dev/dl/{{ go_tarball }}"
    go_install_dir: "/usr/local"
  tasks:
    - name: Download Golang tarball
      get_url:
        url: "{{ go_download_url }}"
        dest: "/tmp/{{ go_tarball }}"
        mode: '0644'
    - name: Extract Golang tarball
      unarchive:
        src: "/tmp/{{ go_tarball }}"
        dest: "{{ go_install_dir }}"
# - import_playbook: ./playbook/vscode/playbook.yml
