---
- name: Install Neovim
  become: true
  hosts: localhost
  tasks:
    - name: Install Neovim package
      ansible.builtin.dnf:
        name: neovim
        state: latest

    - name: Install Vim Plug for Neovim
      ansible.builtin.shell: |
        curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        executable: /bin/bash
      become: false
- name: Clone private Git repository locally using SSH
  hosts: localhost
  become: false
  vars:
    repo_url: "git@github.com:saldyy/neovim-config.git"
    clone_dest: "{{ ansible_user_dir }}/.config/nvim"
    ssh_key_path: "{{ ansible_user_dir }}/.ssh/saldyy_github_tp" 

  tasks:
    - name: Add Git host to known_hosts
      known_hosts:
        path: "~/.ssh/known_hosts"
        name: "github.com"
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        state: present

    - name: Clone the private Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ clone_dest }}"
        version: master
        key_file: "{{ ssh_key_path }}"
        accept_hostkey: yes
        update: yes
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ ssh_key_path }} -o StrictHostKeyChecking=no"
