---
- name: Install Neovim
  become: true
  hosts: localhost

  tasks:
    - name: Install neovim package
      ansible.builtin.dnf:
        name: neovim
        state: latest

    - name: Install Vim Plug
      ansible.builtin.shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: Cloning configuration
      ansible.builtin.git:
        repo: 'git@github.com:saldyy/neovim-config.git'
        dest: './config/nvim'
        version: 'master'
        update: yes
        accept_hostkey: yes
