---
- name: Install Wezterm
  become: true
  hosts: localhost
  tasks:
    - name: Download RPM package
      ansible.builtin.get_url:
        url: https://github.com/wezterm/wezterm/releases/download/nightly/wezterm-nightly-fedora40.rpm
        dest: .
    - name: Install RPM package
      ansible.builtin.command:
        cmd: rpm -ivh ./wezterm-nightly-fedora40.rpm
    - name: Remove RPM package
      ansible.builtin.file:
        path: ./wezterm-nightly-fedora40.rpm
        state: absent
