---
- name: Install zsh shell
  become: true
  hosts: localhost

  tasks:
    - name: Install zsh
      ansible.builtin.dnf:
        name: zsh
        state: latest
    - name: Set ZSH as default shell for user
      command: chsh -s $(wihch zsh)
      changed_when: true  
